// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
    event_type_id,
    starts_at,
    ends_at,
    guest_name,
    guest_email,
    guest_note
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING
    id,
    event_type_id,
    (SELECT title FROM event_types WHERE id = $1) AS event_type_title,
    starts_at,
    ends_at,
    guest_name,
    guest_email,
    guest_note,
    created_at
`

type CreateBookingParams struct {
	EventTypeID pgtype.UUID        `json:"event_type_id"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	EndsAt      pgtype.Timestamptz `json:"ends_at"`
	GuestName   string             `json:"guest_name"`
	GuestEmail  string             `json:"guest_email"`
	GuestNote   *string            `json:"guest_note"`
}

type CreateBookingRow struct {
	ID             pgtype.UUID        `json:"id"`
	EventTypeID    pgtype.UUID        `json:"event_type_id"`
	EventTypeTitle string             `json:"event_type_title"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	EndsAt         pgtype.Timestamptz `json:"ends_at"`
	GuestName      string             `json:"guest_name"`
	GuestEmail     string             `json:"guest_email"`
	GuestNote      *string            `json:"guest_note"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (CreateBookingRow, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.EventTypeID,
		arg.StartsAt,
		arg.EndsAt,
		arg.GuestName,
		arg.GuestEmail,
		arg.GuestNote,
	)
	var i CreateBookingRow
	err := row.Scan(
		&i.ID,
		&i.EventTypeID,
		&i.EventTypeTitle,
		&i.StartsAt,
		&i.EndsAt,
		&i.GuestName,
		&i.GuestEmail,
		&i.GuestNote,
		&i.CreatedAt,
	)
	return i, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    title,
    description,
    starts_at,
    ends_at
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, title, description, starts_at, ends_at, created_at, updated_at
`

type CreateEventParams struct {
	Title       string             `json:"title"`
	Description *string            `json:"description"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	EndsAt      pgtype.Timestamptz `json:"ends_at"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Title,
		arg.Description,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEventType = `-- name: CreateEventType :one
INSERT INTO event_types (
    id,
    title,
    description,
    duration_minutes
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, title, description, duration_minutes, created_at, updated_at
`

type CreateEventTypeParams struct {
	ID              pgtype.UUID `json:"id"`
	Title           string      `json:"title"`
	Description     string      `json:"description"`
	DurationMinutes int32       `json:"duration_minutes"`
}

func (q *Queries) CreateEventType(ctx context.Context, arg CreateEventTypeParams) (EventType, error) {
	row := q.db.QueryRow(ctx, createEventType,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.DurationMinutes,
	)
	var i EventType
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.DurationMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventType = `-- name: GetEventType :one
SELECT id, title, description, duration_minutes, created_at, updated_at
FROM event_types
WHERE id = $1
`

func (q *Queries) GetEventType(ctx context.Context, id pgtype.UUID) (EventType, error) {
	row := q.db.QueryRow(ctx, getEventType, id)
	var i EventType
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.DurationMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBookingsInWindow = `-- name: ListBookingsInWindow :many
SELECT
    b.id,
    b.event_type_id,
    et.title AS event_type_title,
    b.starts_at,
    b.ends_at,
    b.guest_name,
    b.guest_email,
    b.guest_note,
    b.created_at
FROM bookings b
JOIN event_types et ON et.id = b.event_type_id
WHERE b.starts_at < $1
  AND b.ends_at > $2
ORDER BY b.starts_at ASC, b.id ASC
`

type ListBookingsInWindowParams struct {
	WindowEndsAt   pgtype.Timestamptz `json:"window_ends_at"`
	WindowStartsAt pgtype.Timestamptz `json:"window_starts_at"`
}

type ListBookingsInWindowRow struct {
	ID             pgtype.UUID        `json:"id"`
	EventTypeID    pgtype.UUID        `json:"event_type_id"`
	EventTypeTitle string             `json:"event_type_title"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	EndsAt         pgtype.Timestamptz `json:"ends_at"`
	GuestName      string             `json:"guest_name"`
	GuestEmail     string             `json:"guest_email"`
	GuestNote      *string            `json:"guest_note"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListBookingsInWindow(ctx context.Context, arg ListBookingsInWindowParams) ([]ListBookingsInWindowRow, error) {
	rows, err := q.db.Query(ctx, listBookingsInWindow, arg.WindowEndsAt, arg.WindowStartsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingsInWindowRow{}
	for rows.Next() {
		var i ListBookingsInWindowRow
		if err := rows.Scan(
			&i.ID,
			&i.EventTypeID,
			&i.EventTypeTitle,
			&i.StartsAt,
			&i.EndsAt,
			&i.GuestName,
			&i.GuestEmail,
			&i.GuestNote,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventTypes = `-- name: ListEventTypes :many
SELECT id, title, description, duration_minutes, created_at, updated_at
FROM event_types
ORDER BY title ASC, id ASC
`

func (q *Queries) ListEventTypes(ctx context.Context) ([]EventType, error) {
	rows, err := q.db.Query(ctx, listEventTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventType{}
	for rows.Next() {
		var i EventType
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.DurationMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT id, title, description, starts_at, ends_at, created_at, updated_at
FROM events
ORDER BY starts_at ASC, id ASC
LIMIT $1 OFFSET $2
`

type ListEventsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingBookings = `-- name: ListUpcomingBookings :many
SELECT
    b.id,
    b.event_type_id,
    et.title AS event_type_title,
    b.starts_at,
    b.ends_at,
    b.guest_name,
    b.guest_email,
    b.guest_note,
    b.created_at
FROM bookings b
JOIN event_types et ON et.id = b.event_type_id
WHERE b.starts_at >= $1
ORDER BY b.starts_at ASC, b.id ASC
`

type ListUpcomingBookingsRow struct {
	ID             pgtype.UUID        `json:"id"`
	EventTypeID    pgtype.UUID        `json:"event_type_id"`
	EventTypeTitle string             `json:"event_type_title"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	EndsAt         pgtype.Timestamptz `json:"ends_at"`
	GuestName      string             `json:"guest_name"`
	GuestEmail     string             `json:"guest_email"`
	GuestNote      *string            `json:"guest_note"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUpcomingBookings(ctx context.Context, startsAt pgtype.Timestamptz) ([]ListUpcomingBookingsRow, error) {
	rows, err := q.db.Query(ctx, listUpcomingBookings, startsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUpcomingBookingsRow{}
	for rows.Next() {
		var i ListUpcomingBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventTypeID,
			&i.EventTypeTitle,
			&i.StartsAt,
			&i.EndsAt,
			&i.GuestName,
			&i.GuestEmail,
			&i.GuestNote,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
